version: "3.9"
services:
  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: python3 -m pytest
  run:
    build: .
    depends_on:
      - test
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./.env
    entrypoint: sh ./run.sh "" "" "${unloading_url}" "" ""
